name: 'Build'

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('hsparql.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - uses: actions/cache@v3
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('hsparql.cabal') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-
      - name: Install
        run: |
          mkdir -p ~/.local/bin
          export PATH=$HOME/.local/bin:$PATH
          curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      - name: Build
        run: stack --resolver lts --no-terminal --install-ghc test --haddock
